Add pact as a dependency
For some reason this is failing the build with lots of test failures
like these:

```
  Scenario: Creating a new data set with a CSV file in the wrong format                     # features/data_sets.feature:96
    Given I have previously created the "Register Offices" service                          # features/step_definitions/service_steps.rb:1
    When I go to the page for the "Register Offices" service                                # features/step_definitions/service_steps.rb:23
    And I upload a new data set with a CSV in the wrong format                              # features/step_definitions/data_set_steps.rb:16
    Then I should be on the page for the latest data set for the "Register Offices" service # features/step_definitions/data_set_steps.rb:105
      undefined method `+' for nil:NilClass (NoMethodError)
```

This is _despite_ explicitly setting `require: false` on the gem.